# Docker Compose version
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'

# Define the 'internal' network for inter-container communication.
networks:
  internal:
    name: internal
    driver: bridge
    # ipam:
    #     driver: default
    #     config:
    #       - subnet: "172.17.0.0/16"
# Define named volumes for data storage.
volumes:
  wordpress:
    driver: local
    driver_opts:
      device: ~/Desktop/vol/data/wordpress
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: ~/Desktop/vol/data/mariadb
      o: bind
      type: none

# Start of services
services:
# Define nginx service:
  #nginx:
  # depends_on: wordpress
  # container_name: nginx
  # build: .requirements/nginx
  # env_file:
  #   - ../.env
  # expose:
  #   -
  # ports:
  #   - :
  # networks:
  #    - internal
  # volumes:
  #   -wordpress:/var/www/html
  #

# services:
  # Define the 'wordpress' service.
  wordpress:
    container_name: wordpress
    depends_on: 
      mariadb:
        condition: service_healthy
    # Use the official WordPress Docker image.
    image: wordpress:42
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        - DBWP_NAME=${DBWP_NAME}
        - DBWP_USER=${DBWP_USER}
        - DBWP_PWD=${DBWP_PWD}
        - DATABASE_HOST=${DATABASE_HOST}
        - DOMAIN_NAME=${DOMAIN_NAME}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN_USR=${WP_ADMIN_USR}
        - WP_ADMIN_PWD=${WP_ADMIN_PWD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USR=${WP_USR}
        - WP_EMAIL=${WP_EMAIL}
        - WP_PWD=${WP_PWD}
    # env_file:
    #   - .env
    volumes:
      # Mount a local directory as a volume in the container.
      - wordpress:/var/www/html
    networks:
      # Connect to the 'internal' network for communication.
      - internal  
  # Define the MariaDB service.
  mariadb:
    hostname: mariadbinc
    # Use the official MariaDB Docker image.
    container_name: mariadb
    image: mariadb42
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        - DBWP_NAME=${DBWP_NAME}
        - DBWP_USER=${DBWP_USER}
        - DBWP_PWD=${DBWP_PWD}
        - DBWP_ROOT_PWD=${DBWP_ROOT_PWD}
    # env_file:
    #   - .env
    # restart: always
    # Set environment variables for the MariaDB service.
    volumes:
      # Mount a local directory as a volume in the container.
      - db:/var/lib/mysql
    networks: 
      # Connect to the 'internal' network for communication.
      - internal
        # ipv4_address: 172.17.0.2
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mariadb"]
      timeout: 10s
      retries: 5
      # start_period: 30s